name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git Safe Directory
        run: git config --global --add safe.directory /github/workspace

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Change Ownership of Repository
        run: sudo chown -R $(whoami) /github/workspace

      - name: Debug Git Setup
        run: git config --list --show-origin

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: faieemkhan
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated snake
        uses: github-actions-x/commit@v2.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Generate snake animation"
          branch: output
